### ISSUE TITLE
ontopy backend failing tests

### ISSUE THREAD

**Issue by CasperWA** [EMMC-ASBL/tripper#7] opened 2022-10-07 14:24 UTC
The ontopy backend is currently failing the standard Triplestore class test and is therefore disabled. This should be rectified.

**Comment by jesper-friis** [comment] 2022-10-21 22:57
Seems to have been fixed in commit 8ef8b4e4fd0814a47621f5554ae38e7b2e5c379f

I guess this can be closed.

**Comment by CasperWA** [comment] 2022-10-24 08:18
No, the content was not changed in this commit, only moved around. Note [this line](https://github.com/EMMC-ASBL/tripper/commit/8ef8b4e4fd0814a47621f5554ae38e7b2e5c379f#diff-d3a2c73a884ef6a692d33ee402129e62002d3ec4fd28bbd0ed73f2ea0c1f5160R16), where the ontopy backend is specifically skipped.

This issue was created during the development of the PR, containing the commit you're referencing.

**Comment by jesper-friis** [comment] 2022-12-01 15:02
Ok, I took a look at this. The issue is in the test. The output and the expected output are semantically equivalent, but the output and expected output differ in:
* order of prefixes
* choice of prefix for the "current" ontology
* naming of blank nodes

**Comment by jesper-friis** [comment] 2023-01-24 17:28
Closing

**Closed by jesper-friis** 2023-01-24 17:28 UTC
Labels: bug, Priority: Medium
